### ISSUE TITLE
bug for mac

### ISSUE THREAD

**Issue by Ran-Xing** [OpenVPN/openvpn3#139]
Transport Error: socket_protect error (UDP)

I can link normally with my mobile phone, but not with my Mac,
The computer can't link when the mobile phone is off

![image](https://user-images.githubusercontent.com/73819467/104932920-31082e00-59e3-11eb-8f05-cc774c8b5f92.png)

**Comment by zhangjiji03** [comment]
me too

**Comment by Song-HaiFeng** [comment]
me too

**Comment by cdcdx** [comment]
me tooooooooooooo

**Comment by runforprogram** [comment]
i am use it on m1 and Monterey。same bug

**Comment by runforprogram** [comment]
Tunnelblick can work

**Comment by xuxinping** [comment]
me to   

<img width="666" alt="image" src="https://user-images.githubusercontent.com/23325991/161437367-ec9b5e6b-4dbc-4cf0-9eca-2ee2e68cb746.png">

**Comment by effolkronium** [comment]
+++

**Comment by jh-leong** [comment]
me tooooo

**Comment by evan2884** [comment]
me tooooooooo

**Comment by jiangzhiyun-yun** [comment]
me tooooooooo

**Comment by antonb-taod** [comment]
same here

**Comment by schwabe** [comment]
Closing this bug since has no actual information and there seem to be only a flood of useless "me too" responses that also have no detailed information.

**Comment by effolkronium** [comment]
Lmao, did u even tried to investigate it ?

**Comment by antonb-taod** [comment]
I don't know what issue other have, but I was able to solve mine today. 

I was getting an `error calling protected() method` and same logs as mentiones above. I figured out that the file `/var/run/agent_ovpnconnect.sock` didn't exist and apperently the problem was that for any reason the ovpn agent wasn't running. To solve this I had to start `/Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent` manually (I'm using macOS 12.2.1). 

Hope it will help someone.

**Comment by effolkronium** [comment]
Interesting. Thanks

**Comment by effolkronium** [comment]
Interesting. Thanks

**Comment by schwabe** [comment]
@effolkronium the original error is just failing to connect to a UDP server. Any kind of condition can lead to that like no network connection. So without any further information and just hte error message, there is nothing we can do and that is why I closed the ticket.

**Comment by effolkronium** [comment]
@schwabe then it would be better to extend logging for this error, so guys will have a chance to send meaningful reports. Just an idea

**Comment by jh-leong** [comment]
> I don't know what issue other have, but I was able to solve mine today.
> 
> I was getting an `error calling protected() method` and same logs as mentiones above. I figured out that the file `/var/run/agent_ovpnconnect.sock` didn't exist and apparently the problem was that for any reason the ovpn agent wasn't running. To solve this I had to start `/Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent` manually (I'm using macOS 12.2.1).
> 
> Hope it will help someone.

thanks so much man, all works well now.

**Comment by alexsmartens** [comment]
I'm seeing the same problem on an M1 Mac:

```
[Sep 15, 2022, 07:17:13] EVENT: RESOLVE
[Sep 15, 2022, 07:17:13] Contacting
XXX.XXX.XXX.XXX:1194 via UDP
[Sep 15, 2022, 07:17:13] EVENT: WAIT
[Sep 15, 2022, 07:17:13] UnixCommandAgent:
transmitting bypass route to
/var/run/agent_ovpnconnect.sock
"host": "XXX.XXX.XXX.XXX"
"ipv6": false,
"pid": 11202
[Sep 15, 2022, 07:17:13] Transport Error:
socket_protect error (UDP)
[Sep 15, 2022, 07:17:13] Client terminated
restarting in 2000 ms...
```

**Comment by alexsmartens** [comment]
> To solve this I had to start /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent manually (I'm using macOS 12.2.1).

This solved it for me, thanks!

**Comment by alexsmartens** [comment]
@schwabe do you mind reopening this issue? It still persists and needs to be addressed. We will help with the logs and whatever else you need

**Comment by xiaowanxiong52hao** [comment]
「設定→バックグラウンド実行を許可」に「openvpn client」を含む項目のチェックを入れてから解決しました。

**Comment by taopanwoaini** [comment]
$ sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent          this command is all right! thanks up man! thanks you;

**Comment by fatihsari** [comment]
> I don't know what issue other have, but I was able to solve mine today.
> 
> I was getting an `error calling protected() method` and same logs as mentiones above. I figured out that the file `/var/run/agent_ovpnconnect.sock` didn't exist and apparently the problem was that for any reason the ovpn agent wasn't running. To solve this I had to start `/Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent` manually (I'm using macOS M1 12.2.1).
> 
> Hope it will help someone.

Thank you @antonb-taod
I've been having this issue for a few days now and it's because I'm using hardware tokens.
I've fixed with `sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent`.

**Comment by fchienvuhoang** [comment]
> sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent

thanks it work like a charm

**Comment by enderphan94** [comment]
`sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent`

this works!

**Comment by tiny-andr** [comment]
I saw a solution on reddit.it solved my problem.
My machine is macbook air M1, openvpn is 3.4.1 (4522), which is already the latest version, but I still have this error.
Here are the steps mentioned on reddit to fix it.
Run these commands in a terminal:
```
sudo launchctl unload -w /Library/LaunchDaemons/org.openvpn.client.plist
ps auxww | grep ovpnagent
```
you shouldn't see: /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent
```
sudo launchctl load -w /Library/LaunchDaemons/org.openvpn.client.plist
ps auxww | grep ovpnagent
```
you SHOULD see: 1. /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent (owned by root)
Reboot the laptop
Connect to the VPN

**Comment by lucamarogna** [comment]
In my case the problem was that login element had been disabled.
Switching the "OpenVPN Client" toggle to "ON" has solved the issue.

**Comment by yoloz** [comment]
In may case the problean was i disabled "OpenVPN Agent agent_ovpnconnect" service in window 11, just start it and reconnect will ok

**Comment by Monkey-X-Byte** [comment]
cool !!!!!!
sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent

**Comment by Nikecow** [comment]
> 

This fixed it for me. It took me ages to find out 😓

**Comment by effolkronium** [comment]
It need to be fixed in code automatically. Where is the author of the project ?

**Comment by schwabe** [comment]
Please use support.openvpn.net for support with the OpenVPN Connect client. The OpenVPN Connect team unfortunately does not want to participate in issues raised on Github. So the only way to report/fix issues with the Connect client is through the official support.

**Comment by matyle** [comment]
`sudo launchctl load -w /Library/LaunchDaemons/org.openvpn.client.plist` this is worked

**Comment by trungegd** [comment]
> I don't know what issue other have, but I was able to solve mine today.
> 
> I was getting an `error calling protected() method` and same logs as mentiones above. I figured out that the file `/var/run/agent_ovpnconnect.sock` didn't exist and apparently the problem was that for any reason the ovpn agent wasn't running. To solve this I had to start `/Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent` manually (I'm using macOS M1 12.2.1).
> 
> Hope it will help someone.

Many thanks

**Comment by cakiem8x** [comment]
> I don't know what issue other have, but I was able to solve mine today.
> 
> I was getting an `error calling protected() method` and same logs as mentiones above. I figured out that the file `/var/run/agent_ovpnconnect.sock` didn't exist and apparently the problem was that for any reason the ovpn agent wasn't running. To solve this I had to start `/Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent` manually (I'm using macOS M1 12.2.1).
> 
> Hope it will help someone.

Thanks :)

**Comment by gokul1630** [comment]
> `sudo launchctl load -w /Library/LaunchDaemons/org.openvpn.client.plist` this is worked

Thanks, It works well on Macbook Pro m2.

**Comment by bigmother** [comment]
> I don't know what issue other have, but I was able to solve mine today.
> 
> I was getting an `error calling protected() method` and same logs as mentiones above. I figured out that the file `/var/run/agent_ovpnconnect.sock` didn't exist and apparently the problem was that for any reason the ovpn agent wasn't running. To solve this I had to start `/Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent` manually (I'm using macOS M1 12.2.1).
> 
> Hope it will help someone.

it works! Thanks lots!

**Comment by AlessandroStaffolani** [comment]
In my case, I disabled OpenVPN to start when starting my Mac. If you are using OpenVPN Connect and experiencing such an error, ensure that OpenVPN is enabled in `setting > general > login elements`.

**Comment by room34** [comment]
@Atlas-Labs-AU Initially I manually ran the above mentioned command to get it working, but then it occurred to me that I might have turned off some OpenVPN background processes in Login Items in System Preferences/System Settings. I checked there and sure enough, I had. I turned that on, rebooted, and OpenVPN is now working for me without having to manually run the command.

**Comment by n3tb0y** [comment]
room34 +1,  it worked for me as well.  

You need to allow openvpn to run in the background. Settings /  General / Login Items / Allow Background shall be clicked for OpenVPN.  Worth to check since it solved the problem for me

**Comment by agussalimus** [comment]
I'm using a Macbook Pro 2017 Intel. I had the same error when using **OpenVPN Connect 3**. I ran `sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent` but it didn't work.

**The problem was resolved** when uninstalling OpenVPN Connect 3 then using **OpenVPN Connect 2.7.1**.

**Comment by novaflash** [comment]
> **The problem was resolved** when uninstalling OpenVPN Connect 3 then using **OpenVPN Connect 2.7.1**.

I want to leave a warning to all that are still using version **v2** of OpenVPN Connect. It has had absolutely no updates of any kind for going on 3 years now. OpenVPN Connect **v3** however is receiving updates and is safe to use. If you are looking for an alternative, then consider using Tunnelblick for macOS, but I would recommend to not use OpenVPN Connect **v2** anymore.

**Comment by effolkronium** [comment]
`OpenVPN Connect v3 however is receiving updates and is safe to use`

But they cannot release update to resolve this issue for more then 2 years...

**Comment by pranay-kickdrum** [comment]
I'm still facing this. `sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent` worked once but not working anymore. Did everything like reinstalling openvpn client, rebooting laptop. Any help?

**Comment by vrogalskyi** [comment]
Got the same issue. Solved for now bu running `sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent` in the tmux to leave it in background.

**Comment by alievrouw** [comment]
> In my case the problem was that login element had been disabled. Switching the "OpenVPN Client" toggle to "ON" has solved the issue.

This was what did it for me too. I think it's silly that to get the required background agent you must also run the UI at startup.

**Comment by vettom** [comment]
I was able to solve by allowing Openvpn in login items
<img width="457" alt="image" src="https://github.com/OpenVPN/openvpn3/assets/20859413/347d197e-a9f2-43f8-8bd6-9df9ffa48ebc">

**Comment by Beirith** [comment]
thanks, @anton-bubnov-taod! it worked!
`sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent`

**Comment by lucienoz** [comment]
mark

**Comment by meyjsolo** [comment]
> I don't know what issue other have, but I was able to solve mine today.
> 
> I was getting an `error calling protected() method` and same logs as mentiones above. I figured out that the file `/var/run/agent_ovpnconnect.sock` didn't exist and apparently the problem was that for any reason the ovpn agent wasn't running. To solve this I had to start `/Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent` manually (I'm using macOS M1 12.2.1).
> 
> Hope it will help someone.

thanks so much.

**Comment by Lily-404** [comment]
This problem basically needs to be entered every time you restart.
`sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent`

**Comment by lingfeng0303** [comment]
I was able to solve by allowing Openvpn in login items

**Comment by cuishuang** [comment]
sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent 

or

sudo launchctl load /Library/LaunchDaemons/org.openvpn.client.plist

**Comment by bpGusar** [comment]
encountered same problem.
`sudo /Library/Frameworks/OpenVPNConnect.framework/Versions/Current/usr/sbin/ovpnagent` works only if terminal is open
`sudo launchctl load /Library/LaunchDaemons/org.openvpn.client.plist` didn't try

anyway i just reinstalled openvpn connect, it added itself to the background running apps and now works fine

**Comment by iliyahristov** [comment]
> I was able to solve by allowing Openvpn in login items <img alt="image" width="457" src="https://private-user-images.githubusercontent.com/20859413/306611733-347d197e-a9f2-43f8-8bd6-9df9ffa48ebc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDc2NDE1NjgsIm5iZiI6MTc0NzY0MTI2OCwicGF0aCI6Ii8yMDg1OTQxMy8zMDY2MTE3MzMtMzQ3ZDE5N2UtYTlmMi00M2Y4LThiZDYtOWRmOWZmYTQ4ZWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTE5VDA3NTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMGE3OTdlODdkZDMwYjA2ZmU2ZmVhOTliNjNlM2YxYzI2NmVkODhmMGZjYzUzZWJjY2VhYTkyMzk3NDg3OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vvz1KDn2WVJo1GzVK3eAujdInn_Xmsp1bj5SK_vcF8o">

Confirm that this works perfect

**Comment by mouyong** [comment]
This problem basically needs to be entered every time you restart.

solve by this on mac, using https://lemon.qq.com/

<img width="440" height="134" alt="Image" src="https://github.com/user-attachments/assets/4a790947-2b3e-49c0-82a9-0865c33471e6" />

<img width="1403" height="1035" alt="Image" src="https://github.com/user-attachments/assets/45352859-4cb9-40d7-b41e-c1b2fdb2b336" />

<img width="1918" height="1199" alt="Image" src="https://github.com/user-attachments/assets/8339f1b1-8463-4d55-9c85-93b50adcb3ff" />

<img width="1242" height="859" alt="Image" src="https://github.com/user-attachments/assets/966a650a-7c1d-400e-935a-9ca1a6106a42" />

**Comment by beeradmoore** [comment]
Same fix for me was to what @vettom said. I don't use OpenVPN Connect often so I figured why would I want it opening on every login. Surely it would start any missing service on application launch. I was very wrong.

**Comment by alex-oos** [comment]
me too
